import { mutation } from "../_generated/server";

export default mutation({
  handler: async (ctx) => {
    // Check if questions already exist
    const existingQuestions = await ctx.db.query("questions").collect();
    if (existingQuestions.length > 0) {
      console.log("Questions already exist. Skipping seed.");
      return;
    }

    // Get all rules to reference their IDs
    const rules = await ctx.db.query("tajweedRules").collect();
    const ruleMap = new Map(rules.map(rule => [rule.slug, rule._id]));

    const questions = [
      // IDGHAM QUESTIONS (10 questions)
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "Which letters trigger Idgham when noon sakinah or tanween is followed by them?",
        options: ["ي ر م ل و ن", "ب ت ث ج د ذ", "س ش ص ض ط ظ", "ف ق ك ه خ غ"],
        correctOptionIndex: 0,
        explanation: "The letters ي ر م ل و ن trigger Idgham when noon sakinah or tanween comes before them. These are remembered by the phrase 'يرملون'.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "In the phrase 'من يقول', what Tajweed rule applies?",
        options: ["Idgham with Ghunna", "Idgham without Ghunna", "Ikhfa", "Izhar"],
        correctOptionIndex: 0,
        explanation: "The noon sakinah in 'من' followed by 'ي' creates Idgham with Ghunna. The ي is one of the letters ينمو that cause Idgham with nasal sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "Which type of Idgham occurs with the letters ل and ر?",
        options: ["Idgham with Ghunna", "Idgham without Ghunna", "Both types", "Neither"],
        correctOptionIndex: 1,
        explanation: "Letters ل and ر cause Idgham without Ghunna (Idgham Bila Ghunna). The noon or tanween merges completely without nasal sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "In 'من ربه', how is the noon sakinah pronounced?",
        options: ["Clearly pronounced", "Merged with ر without Ghunna", "Merged with ر with Ghunna", "Hidden"],
        correctOptionIndex: 1,
        explanation: "The noon sakinah merges with the ر that follows it without Ghunna, creating a smooth transition where the noon loses its identity.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "What happens to tanween when followed by م in Idgham?",
        options: ["It's pronounced clearly", "It merges with Ghunna", "It's hidden", "It becomes sukoon"],
        correctOptionIndex: 1,
        explanation: "Tanween followed by م undergoes Idgham with Ghunna. The tanween sound merges with the م while maintaining the nasal quality.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "Which phrase demonstrates Idgham without Ghunna?",
        options: ["من يقول", "من ماء", "من لدنه", "من نار"],
        correctOptionIndex: 2,
        explanation: "'من لدنه' shows Idgham without Ghunna because ل causes the noon to merge completely without nasal sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "In Idgham, how many counts does the merged sound typically last?",
        options: ["1 count", "2 counts", "3 counts", "4 counts"],
        correctOptionIndex: 1,
        explanation: "In Idgham with Ghunna, the merged sound with nasal quality lasts for 2 counts, similar to natural Ghunna duration.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "What is the literal meaning of 'Idgham'?",
        options: ["Hiding", "Merging/Assimilation", "Bouncing", "Prolonging"],
        correctOptionIndex: 1,
        explanation: "Idgham literally means 'merging' or 'assimilation', where one letter is absorbed into another, losing its distinct pronunciation.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "In the word 'جنات', if followed by و, what rule applies?",
        options: ["Idgham with Ghunna", "Idgham without Ghunna", "Ikhfa", "Izhar"],
        correctOptionIndex: 0,
        explanation: "The tanween in 'جنات' followed by و creates Idgham with Ghunna, as و is one of the letters ينمو.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "Which letters cause Idgham with Ghunna?",
        options: ["ي ن م و", "ل ر", "All Idgham letters", "ق ط ب ج د"],
        correctOptionIndex: 0,
        explanation: "The letters ي ن م و cause Idgham with Ghunna, remembered by the word 'ينمو'. These maintain the nasal sound during merging.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },

      // IKHFA QUESTIONS (12 questions)
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "How many letters trigger Ikhfa when following noon sakinah or tanween?",
        options: ["13 letters", "15 letters", "17 letters", "19 letters"],
        correctOptionIndex: 1,
        explanation: "There are 15 letters that trigger Ikhfa: ت ث ج د ذ ز س ش ص ض ط ظ ف ق ك. These are all the remaining letters after excluding Izhar, Idgham, and Iqlab letters.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "In Ikhfa, how should the noon sakinah or tanween be pronounced?",
        options: ["Clearly pronounced", "Completely merged", "Hidden with nasal sound", "Bounced"],
        correctOptionIndex: 2,
        explanation: "In Ikhfa, the noon sakinah/tanween is hidden (concealed) but still produces a nasal sound that lasts about 2 counts.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "Which phrase demonstrates Ikhfa?",
        options: ["من يقول", "من ربه", "من قبل", "من بعد"],
        correctOptionIndex: 2,
        explanation: "'من قبل' demonstrates Ikhfa because ق is one of the 15 Ikhfa letters. The noon is hidden with nasal sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "What is the duration of Ghunna in Ikhfa?",
        options: ["1 count", "2 counts", "3 counts", "No Ghunna"],
        correctOptionIndex: 1,
        explanation: "The Ghunna in Ikhfa lasts for 2 counts, similar to other cases of Ghunna like Idgham with Ghunna.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "Which letter group includes all Ikhfa letters?",
        options: ["ت ث ج د ذ ز س ش ص ض ط ظ ف ق ك", "ب م و", "ي ر م ل و ن", "ه خ ع غ ح"],
        correctOptionIndex: 0,
        explanation: "The 15 Ikhfa letters are: ت ث ج د ذ ز س ش ص ض ط ظ ف ق ك. These trigger concealment when following noon sakinah or tanween.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "In the phrase 'أن تقولوا', what rule applies to the tanween?",
        options: ["Ikhfa", "Idgham", "Izhar", "Iqlab"],
        correctOptionIndex: 0,
        explanation: "The tanween in 'أن' is followed by ت which is an Ikhfa letter, so the rule is Ikhfa with nasal concealment.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "What does 'Ikhfa' literally mean?",
        options: ["Merging", "Hiding/Concealment", "Bouncing", "Changing"],
        correctOptionIndex: 1,
        explanation: "Ikhfa literally means 'hiding' or 'concealment'. The noon/tanween is concealed but its nasal effect remains.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "In Ikhfa, where is the tongue positioned?",
        options: ["At the point of noon", "At the point of the following letter", "Between noon and following letter", "At the throat"],
        correctOptionIndex: 2,
        explanation: "In Ikhfa, the tongue is positioned between the articulation point of noon and the following letter, creating the concealed sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "Which phrase shows Ikhfa with the letter ص?",
        options: ["من صلى", "من سار", "من قال", "من بعد"],
        correctOptionIndex: 0,
        explanation: "'من صلى' demonstrates Ikhfa because ص is one of the 15 Ikhfa letters, causing concealment of the noon sakinah.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "In 'جنة تجري', what happens to the tanween?",
        options: ["Clear pronunciation", "Ikhfa with nasal sound", "Complete merging", "Changed to م"],
        correctOptionIndex: 1,
        explanation: "The tanween in 'جنة' followed by ت undergoes Ikhfa, being concealed with a nasal sound lasting 2 counts.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "How does Ikhfa differ from Idgham?",
        options: ["No difference", "Ikhfa has partial merging", "Ikhfa maintains some nasal identity", "Ikhfa is longer"],
        correctOptionIndex: 2,
        explanation: "Unlike Idgham where the noon completely merges, in Ikhfa the noon maintains its nasal identity while being concealed.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "Which phrase demonstrates Ikhfa with ك?",
        options: ["من كان", "من قال", "من لدن", "من رب"],
        correctOptionIndex: 0,
        explanation: "'من كان' shows Ikhfa because ك is one of the 15 Ikhfa letters, causing the noon to be concealed with nasal sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },

      // QALQALAH QUESTIONS (11 questions)
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "Which letters are called Qalqalah letters?",
        options: ["ق ط ب ج د", "ك ت ش س ف", "ر ل م ن", "ه ع ح غ خ"],
        correctOptionIndex: 0,
        explanation: "The Qalqalah letters are ق ط ب ج د, remembered by the phrase 'قطب جد'. These letters create a bouncing sound when they have sukoon.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "When does Qalqalah occur?",
        options: ["When the letter has fatha", "When the letter has sukoon", "When the letter has kasra", "When the letter has dhamma"],
        correctOptionIndex: 1,
        explanation: "Qalqalah occurs when any of the Qalqalah letters (ق ط ب ج د) has sukoon, either in the middle or at the end of a word.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "What are the two types of Qalqalah?",
        options: ["Major and Minor", "Strong and Weak", "Sughra (Lesser) and Kubra (Greater)", "Natural and Forced"],
        correctOptionIndex: 2,
        explanation: "The two types are Qalqalah Sughra (lesser) when the letter is in the middle of a word, and Qalqalah Kubra (greater) when at the end.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "In the word 'يقطين', which letter demonstrates Qalqalah?",
        options: ["ي", "ق", "ط", "ن"],
        correctOptionIndex: 1,
        explanation: "The ق in 'يقطين' has sukoon and is a Qalqalah letter, so it demonstrates Qalqalah Sughra (lesser).",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "When is Qalqalah Kubra (Greater) applied?",
        options: ["At the beginning of words", "In the middle of words", "At the end of words", "With tanween"],
        correctOptionIndex: 2,
        explanation: "Qalqalah Kubra (Greater) is applied when a Qalqalah letter with sukoon appears at the end of a word, making the echo stronger.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "What does 'Qalqalah' literally mean?",
        options: ["Hiding", "Merging", "Shaking/Echoing", "Prolonging"],
        correctOptionIndex: 2,
        explanation: "Qalqalah literally means 'shaking' or 'echoing', referring to the bouncing sound produced by these specific letters.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "In the word 'محيط', which letter shows Qalqalah?",
        options: ["م", "ح", "ي", "ط"],
        correctOptionIndex: 3,
        explanation: "The ط at the end of 'محيط' is a Qalqalah letter with sukoon, demonstrating Qalqalah Kubra (greater).",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "How should the echoing sound in Qalqalah be produced?",
        options: ["With extra air", "By vibrating the vocal cords", "With tongue movement only", "By controlling air pressure"],
        correctOptionIndex: 3,
        explanation: "The Qalqalah echo is produced by controlling air pressure and quick release, creating the characteristic bouncing sound without adding extra vowels.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "In 'يخلق', which type of Qalqalah occurs?",
        options: ["Qalqalah Sughra", "Qalqalah Kubra", "No Qalqalah", "Both types"],
        correctOptionIndex: 1,
        explanation: "The ق at the end of 'يخلق' demonstrates Qalqalah Kubra (greater) because it's a Qalqalah letter with sukoon at word's end.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "Which phrase shows multiple Qalqalah letters?",
        options: ["قد جعل", "من قبل", "في بطن", "كل شيء"],
        correctOptionIndex: 0,
        explanation: "'قد جعل' contains both ق and د, which are Qalqalah letters with sukoon, demonstrating the rule multiple times.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("qalqalah")!,
        prompt: "What should be avoided when pronouncing Qalqalah?",
        options: ["Making it too soft", "Adding vowel sounds", "Making it too short", "Using throat"],
        correctOptionIndex: 1,
        explanation: "When pronouncing Qalqalah, avoid adding extra vowel sounds (like 'قا' instead of 'ق'). The echo should be crisp without additional vowels.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },

      // GHUNNA QUESTIONS (10 questions)
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "How long should natural Ghunna last?",
        options: ["1 count", "2 counts", "3 counts", "4 counts"],
        correctOptionIndex: 1,
        explanation: "Natural Ghunna lasts for 2 counts (harakat). This is the standard duration for the nasal sound in normal circumstances.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "Which letters naturally produce Ghunna?",
        options: ["ن and م only", "All nasal letters", "ي and و", "ر and ل"],
        correctOptionIndex: 0,
        explanation: "The letters ن (noon) and م (meem) naturally produce Ghunna due to their nasal articulation points.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "When is Ghunna most prominent?",
        options: ["With fatha", "With kasra", "With dhamma", "With sukoon and shadda"],
        correctOptionIndex: 3,
        explanation: "Ghunna is most prominent when ن or م has sukoon or shadda, as the nasal quality is extended and emphasized.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "In the word 'إن', how long is the Ghunna?",
        options: ["1 count", "2 counts", "3 counts", "No Ghunna"],
        correctOptionIndex: 1,
        explanation: "The ن with sukoon in 'إن' produces natural Ghunna lasting 2 counts, as it's a noon sakinah.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "What happens to Ghunna when ن or م is followed by another ن or م?",
        options: ["It disappears", "It becomes stronger", "It stays the same", "It becomes shorter"],
        correctOptionIndex: 1,
        explanation: "When ن or م is followed by another ن or م, Ghunna becomes stronger due to the doubling effect (like in Idgham scenarios).",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "Where is Ghunna produced in the mouth?",
        options: ["Throat", "Tongue tip", "Nasal cavity", "Lips"],
        correctOptionIndex: 2,
        explanation: "Ghunna is produced in the nasal cavity, creating the characteristic nasal resonance that distinguishes ن and م.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "In Idgham with Ghunna, how long does the nasal sound last?",
        options: ["1 count", "2 counts", "3 counts", "Variable"],
        correctOptionIndex: 1,
        explanation: "In Idgham with Ghunna, the nasal sound lasts for 2 counts, maintaining the standard Ghunna duration.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "When noon or meem has a vowel (haraka), is Ghunna present?",
        options: ["Yes, full Ghunna", "Yes, but reduced", "No Ghunna", "Only with specific vowels"],
        correctOptionIndex: 1,
        explanation: "When ن or م has a vowel, there's still a natural nasal quality but it's reduced compared to sukoon or shadda cases.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "What is the literal meaning of 'Ghunna'?",
        options: ["Nasal sound", "Throat sound", "Tongue sound", "Lip sound"],
        correctOptionIndex: 0,
        explanation: "Ghunna literally means 'nasal sound' or 'nasalization', referring to the resonance produced through the nasal passage.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ghunna")!,
        prompt: "In which Tajweed rule is Ghunna most emphasized?",
        options: ["Izhar", "Ikhfa", "Iqlab", "All involve Ghunna equally"],
        correctOptionIndex: 1,
        explanation: "Ghunna is most emphasized in Ikhfa, where the noon/tanween is concealed but the nasal sound is prominent for 2 counts.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },

      // MADD QUESTIONS (12 questions)
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "How long is Madd Tabii (Natural Madd)?",
        options: ["1 count", "2 counts", "4 counts", "6 counts"],
        correctOptionIndex: 1,
        explanation: "Madd Tabii (Natural Madd) lasts for 2 counts. This is the basic prolongation that occurs naturally with long vowels.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "What are the three Madd letters?",
        options: ["ا و ي", "ن م ل", "ر ل ن", "ب ت ث"],
        correctOptionIndex: 0,
        explanation: "The three Madd letters are ا و ي when they are preceded by compatible vowels (fatha, dhamma, kasra respectively).",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "How long is Madd Muttasil (Connected Madd)?",
        options: ["2 counts", "4-5 counts", "6 counts", "8 counts"],
        correctOptionIndex: 1,
        explanation: "Madd Muttasil lasts for 4-5 counts when a Madd letter is followed by hamza in the same word (like in 'سماء').",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "Which word demonstrates Madd Muttasil?",
        options: ["قالوا", "سماء", "في", "الذين"],
        correctOptionIndex: 1,
        explanation: "'سماء' demonstrates Madd Muttasil because the Madd letter ا is followed by hamza in the same word.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "What is Madd Munfasil (Separated Madd)?",
        options: ["Madd followed by hamza in same word", "Madd followed by hamza in different word", "Natural Madd", "Madd at word end"],
        correctOptionIndex: 1,
        explanation: "Madd Munfasil occurs when a Madd letter at the end of a word is followed by hamza at the beginning of the next word.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "How long can Madd Munfasil be prolonged?",
        options: ["2 counts only", "4 counts only", "2, 4, or 5 counts", "6 counts only"],
        correctOptionIndex: 2,
        explanation: "Madd Munfasil can be prolonged for 2, 4, or 5 counts depending on the recitation style (qira'ah) being followed.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "In 'قالوا آمنوا', what type of Madd occurs?",
        options: ["Madd Tabii", "Madd Muttasil", "Madd Munfasil", "No Madd"],
        correctOptionIndex: 2,
        explanation: "'قالوا آمنوا' demonstrates Madd Munfasil because the ا at the end of 'قالوا' is followed by hamza in 'آمنوا'.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "What must precede the Madd letters for proper Madd?",
        options: ["Any vowel", "Compatible vowels", "Sukoon", "Shadda"],
        correctOptionIndex: 1,
        explanation: "For proper Madd, the letters must be preceded by compatible vowels: ا needs fatha, و needs dhamma, ي needs kasra.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "Which phrase shows natural Madd only?",
        options: ["سماء", "قالوا آمنوا", "قال", "هؤلاء"],
        correctOptionIndex: 2,
        explanation: "'قال' shows only natural Madd Tabii (2 counts) because the ا is not followed by hamza or other lengthening factors.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "What does 'Madd' literally mean?",
        options: ["Shortening", "Lengthening/Prolongation", "Stopping", "Softening"],
        correctOptionIndex: 1,
        explanation: "Madd literally means 'lengthening' or 'prolongation', referring to the extension of vowel sounds beyond their natural length.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "In 'يا أيها', what happens to the Madd?",
        options: ["2 counts", "4-5 counts", "6 counts", "No Madd"],
        correctOptionIndex: 1,
        explanation: "In 'يا أيها', the ا at the end of 'يا' followed by hamza in 'أيها' creates Madd Munfasil (4-5 counts).",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("madd")!,
        prompt: "Which type of Madd is considered obligatory (wajib)?",
        options: ["Madd Tabii", "Madd Muttasil", "Madd Munfasil", "All types"],
        correctOptionIndex: 1,
        explanation: "Madd Muttasil is considered wajib (obligatory) and must be prolonged to 4-5 counts, while Madd Munfasil has flexibility in some recitation styles.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
    ];

    // Insert all questions
    for (const question of questions) {
      await ctx.db.insert("questions", question);
    }

    console.log(`Successfully seeded ${questions.length} questions`);
    return { success: true, count: questions.length };
  },
});