import { mutation } from "../_generated/server";

export default mutation({
  handler: async (ctx) => {
    console.log("🔄 Starting question simplification...");

    // Get all rules to reference their IDs
    const rules = await ctx.db.query("tajweedRules").collect();
    const ruleMap = new Map(rules.map(rule => [rule.slug, rule._id]));


    // Delete existing questions
    const existingQuestions = await ctx.db.query("questions").collect();
    for (const question of existingQuestions) {
      await ctx.db.delete(question._id);
    }
    console.log(`🗑️ Deleted ${existingQuestions.length} existing questions`);

    const simplifiedQuestions = [
      // IDGHAM QUESTIONS - Super Clear & Simple
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "Which 6 letters make sounds join together?",
        options: ["ي ر م ل و ن", "ب ت ث ج د ذ", "س ش ص ض ط ظ", "ف ق ك ه خ غ"],
        correctOptionIndex: 0,
        explanation: "These 6 letters: ي ر م ل و ن make sounds join together. Remember: Ya-Ra-Meem-Lam-Wow-Noon.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "When you say 'من يقول', what should you do?",
        options: ["Join the ن and ي sounds together with Ghunnah", "Say ن clearly, then ي", "Skip the ن sound", "Say ن loudly"],
        correctOptionIndex: 0,
        explanation: "Join the ن and ي sounds together and make a gentle Ghunnah sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "When ن meets ل or ر, do you make a Ghunnah sound?",
        options: ["Yes, always Ghunnah", "No, join smoothly without Ghunnah", "Sometimes Ghunnah", "Never join them"],
        correctOptionIndex: 1,
        explanation: "No Ghunnah! When ن meets ل or ر, just join them smoothly together.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "How should you say 'من ربه'?",
        options: ["Say ن clearly, then ر", "Join ن and ر smoothly (no Ghunnah)", "Hum between ن and ر", "Skip the ن"],
        correctOptionIndex: 1,
        explanation: "Join the ن and ر smoothly together without any Ghunnah.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "Which 4 letters make you use use Ghunnah when joining?",
        options: ["ي ن م و", "ل ر ن م", "ب ت ث ج", "All letters"],
        correctOptionIndex: 0,
        explanation: "Only these 4 letters: ي ن م و make you use use Ghunnah when joining. Remember: Ya-Noon-Meem-Wow.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "What does 'joining sounds' mean?",
        options: ["Say each sound separately", "Mix two sounds into one", "Make sounds louder", "Skip some sounds"],
        correctOptionIndex: 1,
        explanation: "Joining sounds means mixing two sounds together so they become one smooth sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "When you Ghunnah, how long should it last?",
        options: ["Very quick", "Count 1-2", "Count 1-2-3", "Very long"],
        correctOptionIndex: 1,
        explanation: "When you Ghunnah, count 1-2. That's the right length - not too short, not too long.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "In 'من لدنه', should you Ghunnah?",
        options: ["Yes, Ghunnah", "No, join smoothly", "Sometimes", "Say clearly"],
        correctOptionIndex: 1,
        explanation: "No Ghunnah! Just join the ن and ل smoothly together.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "Which word needs use Ghunnah when you join the sounds?",
        options: ["من ربه", "من لدنه", "من يقول", "All of them"],
        correctOptionIndex: 2,
        explanation: "'من يقول' needs Ghunnah because ي is one of the 4 letters that make you use Ghunnah.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("idgham")!,
        prompt: "When ن meets و, what do you do?",
        options: ["Say them separately", "Join them with Ghunnah", "Join them without Ghunnah", "Skip the ن"],
        correctOptionIndex: 1,
        explanation: "Join the ن and و together and make a gentle Ghunnah sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },

      // IKHFA QUESTIONS - Super Clear & Simple
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "How many letters make you 'hide' the ن sound?",
        options: ["10 letters", "15 letters", "20 letters", "All letters"],
        correctOptionIndex: 1,
        explanation: "15 letters make you hide the ن sound but still Ghunnah gently.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "When hiding the ن sound, what do you do?",
        options: ["Say ن clearly", "Join completely", "Hide ن but Ghunnah gently", "Skip the ن"],
        correctOptionIndex: 2,
        explanation: "Hide the ن sound but still make a gentle Ghunnah sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "In 'من قبل', what should you do?",
        options: ["Say ن clearly", "Join ن and ق", "Hide ن but Ghunnah gently", "Skip ن"],
        correctOptionIndex: 2,
        explanation: "Hide the ن sound but make a gentle Ghunnah before saying ق.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "What does 'hiding' the sound mean?",
        options: ["Skip it completely", "Say it very loudly", "Don't say it clearly but still Ghunnah", "Change it to another sound"],
        correctOptionIndex: 2,
        explanation: "Hiding means you don't say the ن clearly, but you still make a gentle Ghunnah sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "How long should you use Ghunnah when hiding ن?",
        options: ["Don't Ghunnah", "Count 1", "Count 1-2", "Count 1-2-3"],
        correctOptionIndex: 2,
        explanation: "Hum gently for 1-2 counts when hiding the ن sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "In 'منْ تحت', what happens to the ن?",
        options: ["Say it clearly", "Hide it and Ghunnah gently", "Join it with ت", "Skip it"],
        correctOptionIndex: 1,
        explanation: "Hide the ن and make a gentle Ghunnah sound before the ت.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "Which letter makes you hide the ن?",
        options: ["ي", "ر", "ت", "ب"],
        correctOptionIndex: 2,
        explanation: "ت is one of the 15 letters that makes you hide the ن sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "When hiding ن, where should your tongue be?",
        options: ["Touch the next letter's place", "Stay in the middle (don't touch anywhere)", "Touch your teeth", "Touch the roof"],
        correctOptionIndex: 1,
        explanation: "Keep your tongue in the middle - don't touch anywhere specific when hiding ن.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "What kind of Ghunnah do you make when hiding ن?",
        options: ["Loud Ghunnah", "Gentle, soft Ghunnah", "No Ghunnah", "Very long Ghunnah"],
        correctOptionIndex: 1,
        explanation: "Make a gentle, soft Ghunnah sound when hiding the ن.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ikhfa")!,
        prompt: "Which shows correct hiding of ن?",
        options: ["من صالح", "من يقول", "من ربه", "من بيت"],
        correctOptionIndex: 0,
        explanation: "'من صالح' shows hiding because ص is one of the 15 hiding letters.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },

      // IQLAB QUESTIONS - Super Clear & Simple
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "Which letter makes ن change to م?",
        options: ["ب only", "ر only", "ي only", "م only"],
        correctOptionIndex: 0,
        explanation: "Only the letter ب makes ن change to م. Just this one letter!",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "When ن meets ب, what sound do you make instead?",
        options: ["ي sound", "و sound", "م sound", "ر sound"],
        correctOptionIndex: 2,
        explanation: "When ن meets ب, change the ن to a م sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "How should you say 'من بعد'?",
        options: ["Say: من بعد", "Say: مم بعد (with Ghunnah)", "Say: من ـعد", "Say: مب بعد"],
        correctOptionIndex: 1,
        explanation: "Say 'مم بعد' - change the ن to م and make a gentle Ghunnah sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "What does 'changing the sound' mean?",
        options: ["Make it louder", "Say a different sound instead", "Skip it", "Say it twice"],
        correctOptionIndex: 1,
        explanation: "Changing means you say a different sound - م instead of ن.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "When changing ن to م, what do you do with your lips?",
        options: ["Keep lips open", "Close lips gently (don't touch completely)", "Press lips tightly", "Move lips quickly"],
        correctOptionIndex: 1,
        explanation: "Close your lips gently to make the م sound, but don't press them tightly together.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "How long should you use Ghunnah when changing ن to م?",
        options: ["Don't Ghunnah", "Count 1-2", "Count 1-2-3", "Count very long"],
        correctOptionIndex: 1,
        explanation: "Hum gently for 1-2 counts when changing ن to م.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "Which word shows changing ن to م?",
        options: ["أن يقول", "من تحت", "من بيت", "من ربه"],
        correctOptionIndex: 2,
        explanation: "'من بيت' shows changing because ن meets ب, so ن becomes م.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "In the word 'عنب', what happens?",
        options: ["Nothing changes", "ن becomes م (say: عمب)", "ب disappears", "Both sounds join"],
        correctOptionIndex: 1,
        explanation: "The ن changes to م, so you say 'عمب' with gentle Ghunnah.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "Why does ن change to م before ب?",
        options: ["Both م and ب use your lips", "It sounds prettier", "It's easier to remember", "It's a random rule"],
        correctOptionIndex: 0,
        explanation: "ن changes to م because both م and ب are made with your lips, making it easier to say.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("iqlaab")!,
        prompt: "Do you use Ghunnah when changing ن to م?",
        options: ["No Ghunnah ever", "Yes, gentle Ghunnah", "Yes, loud Ghunnah", "Sometimes Ghunnah"],
        correctOptionIndex: 1,
        explanation: "Yes, make gentle use Ghunnah when you change ن to م.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },

      // IZHAR QUESTIONS - Super Clear & Simple
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "How many letters make you say ن clearly?",
        options: ["4 letters", "6 letters", "8 letters", "10 letters"],
        correctOptionIndex: 1,
        explanation: "6 letters make you say ن clearly: أ ه ع غ ح خ (throat letters).",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "When you see these 6 letters after ن, what do you do?",
        options: ["Hide the ن", "Join the sounds", "Say ن clearly and separately", "Hum gently"],
        correctOptionIndex: 2,
        explanation: "Say the ن clearly and separately - don't join, hide, or Ghunnah.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "In 'من عند', how should you say the ن?",
        options: ["Hide it", "Join it with ع", "Say it clearly, then ع", "Change it to م"],
        correctOptionIndex: 2,
        explanation: "Say the ن clearly, then say ع. Keep them separate.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "What does 'saying clearly' mean?",
        options: ["Say very loudly", "Say each sound separately and distinctly", "Say very quickly", "Say with Ghunnah"],
        correctOptionIndex: 1,
        explanation: "Saying clearly means pronounce each sound separately and distinctly.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "Where are these 6 clear-saying letters made?",
        options: ["With your lips", "With your tongue tip", "In your throat", "With your teeth"],
        correctOptionIndex: 2,
        explanation: "These 6 letters are made in your throat, so they're called throat letters.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "When saying ن clearly, do you Ghunnah?",
        options: ["Yes, always Ghunnah", "No, never Ghunnah", "Sometimes Ghunnah", "Hum very quietly"],
        correctOptionIndex: 1,
        explanation: "No Ghunnah! Just say the ن clearly without any nasal sound.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "How should you say 'من أجل'?",
        options: ["Hide the ن", "Join ن and أ", "Say ن clearly, then أ", "Change ن to م"],
        correctOptionIndex: 2,
        explanation: "Say the ن clearly, then say أ. Keep them separate because أ is a throat letter.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "Which letter makes you say ن clearly?",
        options: ["ب", "ت", "ح", "ق"],
        correctOptionIndex: 2,
        explanation: "ح is one of the 6 throat letters that makes you say ن clearly.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "How long should you hold the ن when saying it clearly?",
        options: ["Very short", "Normal length (not extra long)", "Count 1-2", "Very long"],
        correctOptionIndex: 1,
        explanation: "Hold the ن for normal length - not extra short or extra long.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
      {
        ruleId: ruleMap.get("ith-har")!,
        prompt: "What makes clear-saying different from other rules?",
        options: ["It has Ghunnah", "It changes the ن", "It keeps ن separate and clear", "It hides the ن"],
        correctOptionIndex: 2,
        explanation: "Clear-saying is different because it keeps the ن separate and clear - no joining, hiding, or changing.",
        isActive: true,
        version: 1,
        createdAt: Date.now(),
      },
    ];

    // Insert all questions
    let insertedCount = 0;
    for (const question of simplifiedQuestions) {
      await ctx.db.insert("questions", question);
      insertedCount++;
    }

    console.log(`✅ Successfully created ${insertedCount} ultra-clear questions`);
    return { count: insertedCount };
  },
});